name:
  export_plugin

on:
  workflow_dispatch:
    inputs:
      RELEASE_NAME:
        description: 'release name'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo' # タイムゾーン指定
      run: echo "CURRENT_DATETIME=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    - name: Create Plugin Directory
      run: |
        find . -type f | grep -ve './.git' -ve './.vscode' -ve '__pycache__/' | xargs -I src rsync -R src qgis-jaxa-earth-plugin-master
    - name: Create Archive
      run: |
        zip -r qgis-jaxa-earth-plugin-master.zip ./qgis-jaxa-earth-plugin-master
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{env.CURRENT_DATETIME}}
        release_name: ${{github.event.inputs.RELEASE_NAME }}

    - name: Upload GitHub Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./qgis-jaxa-earth-plugin-master.zip
        asset_name: qgis-jaxa-earth-plugin-master.zip
        asset_content_type: application/zip